import type { ItineraryResponse } from "@/types/itinerary";

export const sampleNewYorkItinerary: ItineraryResponse = {
  destination: "New York City",
  editorial:
    "Where every borough is a world and every block an invitation — New York never performs; it simply is.",

  // ─── Recommended Stays ────────────────────────────────────────────────────
  recommendedStays: [
    // Boutique tier
    {
      name: "The Bowery Hotel",
      description:
        "A Gothic-Victorian brick landmark on the edge of NoHo, The Bowery trades on moody interiors, a legendary terrace bar, and a location that puts the Lower East Side at your door. It is the kind of hotel that feels like it belongs to the neighbourhood.",
      neighborhood: "NoHo / Lower East Side",
      rating: 3,
      priceTier: "$$$",
    },
    {
      name: "The Jane Hotel",
      description:
        "Originally a sailors' boardinghouse, The Jane has been reborn as a design cult object — compact cabins with nautical detailing, a grand ballroom bar, and a West Village waterfront address that no amount of money can replicate.",
      neighborhood: "West Village Waterfront",
      rating: 3,
      priceTier: "$$$",
    },
    // Premium tier
    {
      name: "The NoMad Hotel",
      description:
        "Jacques Garcia designed the interiors like a Parisian mansion transplanted to Flatiron, all dark wood, bookshelves, and velvet. The restaurant by Daniel Humm made it a culinary destination before the rooms even filled.",
      neighborhood: "Flatiron / NoMad",
      rating: 4,
      priceTier: "$$$$",
    },
    {
      name: "1 Hotel Central Park",
      description:
        "Biophilic design — living walls, reclaimed timber, locally sourced stone — meets a rooftop pool overlooking the park. 1 Hotel proves that luxury and sustainability are not a trade-off when you have a Central Park South address.",
      neighborhood: "Central Park South",
      rating: 4,
      priceTier: "$$$$",
    },
    // Luxury tier
    {
      name: "The Mark Hotel",
      description:
        "Jacques Grange's boldly monochrome interiors sit behind an understated Madison Avenue façade, hiding the city's largest hotel suite and a martini bar so good regulars treat it as a private club. Upper East Side discretion, maximalist soul.",
      neighborhood: "Upper East Side",
      rating: 5,
      priceTier: "$$$$$",
    },
    {
      name: "The Plaza Hotel",
      description:
        "The Plaza needs no introduction — 102 years of presidents, film sets, and Eloise have ensured that. The Edwardian limestone exterior and gilded Palm Court remain the city's most theatrical entrance, and the corner suites overlook both Fifth Avenue and the park.",
      neighborhood: "Fifth Avenue at Central Park",
      rating: 5,
      priceTier: "$$$$$",
    },
  ],

  // ─── Days ─────────────────────────────────────────────────────────────────
  days: [
    // ── DAY 1 ────────────────────────────────────────────────────────────────
    {
      day: 1,
      theme: "The High Line & the West Village",
      pace: "relaxed",
      hiddenGem:
        "Arrive on Gansevoort Street at dusk before the Meatpacking District fills. The original Belgian cobblestones, loading docks, and 19th-century warehouse brickwork are briefly visible under golden light before the clubs open and the spell is broken.",
      hiddenGemCoordinates: { lat: 40.7397, lng: -74.0082 },
      timeline: [
        {
          type: "breakfast",
          title: "Balthazar",
          description:
            "SoHo's grande dame French brasserie — zinc bar, banquettes, and a basket of viennoiserie that has been making the neighbourhood jealous since 1997. Arrive early: the noise level rises with the croissant count.",
          duration: "",
          startTime: "09:00",
          coordinates: { lat: 40.7229, lng: -74.0026 },
          cuisine: "French Brasserie",
          pricePoint: "$$$",
          reservation: true,
          rating: 4.5,
          userRatingsTotal: 8200,
          hoursOpen: "8:00 AM – 12:00 AM",
          priceLevel: 3,
        },
        {
          type: "activity",
          title: "The High Line",
          description:
            "An abandoned freight rail line elevated 30 feet above Chelsea, the High Line has been transformed into a linear park of native plantings, public art, and panoramic Hudson views. The section between 14th and 30th Streets takes 90 minutes at an unhurried pace.",
          duration: "1.5 hours",
          startTime: "10:30",
          category: "CULTURE",
          coordinates: { lat: 40.7480, lng: -74.0048 },
          photoUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=400&q=80",
          rating: 4.8,
          userRatingsTotal: 62000,
          hoursOpen: "7:00 AM – 10:00 PM",
          priceLevel: 0,
          transitFromPrevious: { walkingMinutes: 18, drivingMinutes: 7 },
        },
        {
          type: "lunch",
          title: "Chelsea Market",
          description:
            "A converted Nabisco factory housing 35 vendors under one roof — the lobster rolls at The Lobster Place, tacos at Los Tacos No. 1, and the bread from Amy's Bread are the non-negotiables. Eat standing; everyone else does.",
          duration: "",
          startTime: "12:30",
          coordinates: { lat: 40.7424, lng: -74.0060 },
          cuisine: "Market / Multi-vendor",
          pricePoint: "$$",
          reservation: false,
          rating: 4.6,
          userRatingsTotal: 29000,
          hoursOpen: "8:00 AM – 9:00 PM",
          priceLevel: 2,
          transitFromPrevious: { walkingMinutes: 8, drivingMinutes: 3 },
        },
        {
          type: "activity",
          title: "Whitney Museum of American Art",
          description:
            "Renzo Piano's Meatpacking building is itself a statement — asymmetric, industrial, with outdoor terraces cantilevered over the Hudson. The permanent collection of 20th-century American art (Hopper, O'Keeffe, Basquiat) is among the finest on the continent.",
          duration: "2 hours",
          startTime: "14:30",
          category: "MUSEUM",
          coordinates: { lat: 40.7396, lng: -74.0089 },
          photoUrl: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=400&q=80",
          rating: 4.7,
          userRatingsTotal: 18500,
          hoursOpen: "10:30 AM – 6:00 PM",
          priceLevel: 2,
          transitFromPrevious: { walkingMinutes: 6, drivingMinutes: 3 },
        },
        {
          type: "dinner",
          title: "The Standard Grill",
          description:
            "Below the High Line's 13th Street ramp, The Standard Grill operates as the neighbourhood's informal town square — excellent dry-aged beef, the city's best fries, and a room where fashion editors and Meatpacking regulars have been eating side by side for fifteen years.",
          duration: "",
          startTime: "20:00",
          coordinates: { lat: 40.7402, lng: -74.0073 },
          cuisine: "American Grill",
          pricePoint: "$$$",
          reservation: true,
          rating: 4.4,
          userRatingsTotal: 5800,
          hoursOpen: "7:00 AM – 2:00 AM",
          priceLevel: 3,
          transitFromPrevious: { walkingMinutes: 5, drivingMinutes: 2 },
        },
      ],
    },

    // ── DAY 2 ────────────────────────────────────────────────────────────────
    {
      day: 2,
      theme: "Midtown Masterworks",
      pace: "moderate",
      hiddenGem:
        "Paley Park on East 53rd Street is a 42-by-100-foot pocket park with a 20-foot waterfall that generates enough white noise to completely erase Midtown. It is owned by a private foundation, free to enter, and almost no tourist map marks it.",
      hiddenGemCoordinates: { lat: 40.7602, lng: -73.9715 },
      timeline: [
        {
          type: "breakfast",
          title: "Bouchon Bakery",
          description:
            "Thomas Keller's bakery at Columbus Circle is the most civilised way to start a Midtown day — perfect croissants, a TKO sandwich, and macarons that bear no resemblance to their airport counterparts. The terrace overlooks Central Park South.",
          duration: "",
          startTime: "08:30",
          coordinates: { lat: 40.7685, lng: -73.9829 },
          cuisine: "French Bakery",
          pricePoint: "$$",
          reservation: false,
          rating: 4.5,
          userRatingsTotal: 3200,
          hoursOpen: "8:00 AM – 7:00 PM",
          priceLevel: 2,
        },
        {
          type: "activity",
          title: "Museum of Modern Art (MoMA)",
          description:
            "The 2019 expansion by Diller Scofidio + Renfro added 47,000 square feet but wisely left the sculpture garden untouched. Monet's Water Lilies, Picasso's Les Demoiselles, and the design collection deserve the full morning — three hours is the minimum.",
          duration: "3 hours",
          startTime: "10:00",
          category: "MUSEUM",
          coordinates: { lat: 40.7614, lng: -73.9776 },
          photoUrl: "https://images.unsplash.com/photo-1541535650810-10d26f5c2ab3?w=400&q=80",
          rating: 4.8,
          userRatingsTotal: 71000,
          hoursOpen: "10:30 AM – 5:30 PM",
          priceLevel: 2,
          transitFromPrevious: { walkingMinutes: 22, drivingMinutes: 8 },
        },
        {
          type: "lunch",
          title: "The Modern",
          description:
            "Gabriel Kreuther's two-Michelin-star restaurant occupies the ground floor of MoMA itself, its dining room framing the sculpture garden. The bar room lunch — three courses with a view of Maillol bronzes — is the best-value fine-dining experience in the city.",
          duration: "",
          startTime: "13:00",
          coordinates: { lat: 40.7614, lng: -73.9776 },
          cuisine: "Contemporary French",
          pricePoint: "$$$$",
          reservation: true,
          rating: 4.7,
          userRatingsTotal: 2100,
          hoursOpen: "12:00 PM – 2:30 PM",
          priceLevel: 4,
          transitFromPrevious: { walkingMinutes: 2, drivingMinutes: 1 },
        },
        {
          type: "activity",
          title: "Top of the Rock",
          description:
            "The 70th-floor observation deck of 30 Rockefeller Plaza offers the one view of New York that includes the Empire State Building — something the Empire State Building itself famously cannot. Book the last slot before sunset for both the skyline in gold and the city in lights.",
          duration: "1.5 hours",
          startTime: "15:00",
          category: "SIGHTSEEING",
          coordinates: { lat: 40.7587, lng: -73.9787 },
          photoUrl: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=400&q=80",
          rating: 4.8,
          userRatingsTotal: 54000,
          hoursOpen: "9:00 AM – 11:00 PM",
          priceLevel: 2,
          transitFromPrevious: { walkingMinutes: 5, drivingMinutes: 2 },
        },
        {
          type: "drinks",
          title: "King Cole Bar at The St. Regis",
          description:
            "The Bloody Mary was invented at this bar in 1934, and Maxfield Parrish's vast mural of Old King Cole has not moved since. Order the house Bloody Mary and take the corner banquette — the room has more history per square foot than most museums.",
          duration: "1 hour",
          startTime: "19:30",
          coordinates: { lat: 40.7607, lng: -73.9739 },
          pricePoint: "$$$",
          reservation: false,
          rating: 4.6,
          userRatingsTotal: 4100,
          hoursOpen: "11:30 AM – 1:00 AM",
          priceLevel: 4,
          transitFromPrevious: { walkingMinutes: 9, drivingMinutes: 4 },
        },
        {
          type: "dinner",
          title: "Le Bernardin",
          description:
            "Éric Ripert's four-star temple to the sea has held its Michelin stars for 38 consecutive years — a record that speaks to a kitchen where technique is invisible and the fish is always the first voice in the room. The tasting menu is non-negotiable.",
          duration: "",
          startTime: "21:00",
          coordinates: { lat: 40.7615, lng: -73.9817 },
          cuisine: "Contemporary French Seafood",
          pricePoint: "$$$$",
          reservation: true,
          dietaryNote: "Pescatarian-friendly throughout; notify on booking for dietary needs.",
          rating: 4.8,
          userRatingsTotal: 6800,
          hoursOpen: "5:30 PM – 10:30 PM",
          priceLevel: 4,
          transitFromPrevious: { walkingMinutes: 12, drivingMinutes: 5 },
        },
      ],
    },

    // ── DAY 3 ────────────────────────────────────────────────────────────────
    {
      day: 3,
      theme: "Brooklyn Bridge to Tribeca",
      pace: "packed",
      hiddenGem:
        "The Elevated Acre at 55 Water Street is a rooftop garden above FiDi accessible via a public escalator on Old Slip. Half an acre of lawn, East River views, and zero foot traffic — the financial district's best secret costs nothing and appears on almost no tourist itinerary.",
      hiddenGemCoordinates: { lat: 40.7028, lng: -74.0104 },
      timeline: [
        {
          type: "breakfast",
          title: "Russ & Daughters Cafe",
          description:
            "The cafe offshoot of the 1914 appetising shop brings lox, whitefish salad, and Eastern European Jewish deli culture to a sit-down room on Orchard Street. The Classic Board — four caviars, crème fraîche, and blinis — is the correct order.",
          duration: "",
          startTime: "08:00",
          coordinates: { lat: 40.7222, lng: -73.9875 },
          cuisine: "Jewish Deli / Appetising",
          pricePoint: "$$$",
          reservation: true,
          rating: 4.6,
          userRatingsTotal: 4700,
          hoursOpen: "8:00 AM – 4:00 PM",
          priceLevel: 3,
        },
        {
          type: "activity",
          title: "Brooklyn Bridge Walk",
          description:
            "The 1.1-mile pedestrian promenade above the roadway takes 30 minutes at pace, but budget an hour for the Gothic limestone towers, the web of steel cables, and the Manhattan skyline unfolding behind you on the return. Cross from Manhattan side to Brooklyn for the classic composition.",
          duration: "1 hour",
          startTime: "09:30",
          category: "ADVENTURE",
          coordinates: { lat: 40.7061, lng: -73.9969 },
          photoUrl: "https://images.unsplash.com/photo-1546436836-07a91091f160?w=400&q=80",
          rating: 4.8,
          userRatingsTotal: 98000,
          hoursOpen: "Open 24 hours",
          priceLevel: 0,
          transitFromPrevious: { walkingMinutes: 25, drivingMinutes: 10 },
        },
        {
          type: "activity",
          title: "DUMBO, Brooklyn",
          description:
            "Down Under the Manhattan Bridge Overpass occupies a cobblestone precinct beneath two suspension bridges, with independent galleries, the Brooklyn Ice Cream Factory, and the most photographed corner in New York — Washington Street framing the Manhattan Bridge tower.",
          duration: "1 hour",
          startTime: "11:00",
          category: "SIGHTSEEING",
          coordinates: { lat: 40.7033, lng: -73.9893 },
          photoUrl: "https://images.unsplash.com/photo-1555109307-f7d9da25c244?w=400&q=80",
          rating: 4.7,
          userRatingsTotal: 22000,
          hoursOpen: "Open 24 hours",
          priceLevel: 1,
          transitFromPrevious: { walkingMinutes: 12, drivingMinutes: 5 },
        },
        {
          type: "lunch",
          title: "Juliana's Pizza",
          description:
            "Patsy Grimaldi's coal-fired pies in a DUMBO basement draw a queue that begins before the doors open — the wait is part of the ritual. A Margherita and a vodka slice are the canonical order; do not deviate.",
          duration: "",
          startTime: "13:00",
          coordinates: { lat: 40.7027, lng: -73.9933 },
          cuisine: "Neapolitan Pizza",
          pricePoint: "$$",
          reservation: false,
          rating: 4.5,
          userRatingsTotal: 8900,
          hoursOpen: "11:30 AM – 10:00 PM",
          priceLevel: 2,
          transitFromPrevious: { walkingMinutes: 8, drivingMinutes: 3 },
        },
        {
          type: "activity",
          title: "9/11 Memorial & Museum",
          description:
            "The two reflecting pools occupy the exact footprints of the Twin Towers, their names inscribed in bronze at the water's edge. The underground museum is among the most thoughtfully designed memorial spaces in the world — plan 90 minutes minimum and allow time to absorb it.",
          duration: "1.5 hours",
          startTime: "15:00",
          category: "CULTURE",
          coordinates: { lat: 40.7115, lng: -74.0134 },
          photoUrl: "https://images.unsplash.com/photo-1575999502951-4ab25b5ca889?w=400&q=80",
          rating: 4.8,
          userRatingsTotal: 71000,
          hoursOpen: "9:00 AM – 8:00 PM",
          priceLevel: 2,
          transitFromPrevious: { walkingMinutes: 28, drivingMinutes: 11 },
        },
        {
          type: "dinner",
          title: "Nobu Tribeca",
          description:
            "The original Nobu — opened by Matsuhisa, De Niro, and Meier in 1994 — still sets the standard for Japanese-Peruvian omakase that the 40 locations that followed have tried to replicate. The black cod miso and yellowtail jalapeño remain the two dishes that defined an era.",
          duration: "",
          startTime: "20:00",
          coordinates: { lat: 40.7238, lng: -74.0069 },
          cuisine: "Japanese-Peruvian",
          pricePoint: "$$$$",
          reservation: true,
          rating: 4.6,
          userRatingsTotal: 7200,
          hoursOpen: "5:30 PM – 11:00 PM",
          priceLevel: 4,
          transitFromPrevious: { walkingMinutes: 18, drivingMinutes: 7 },
        },
      ],
    },
  ],
};
