export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/db";
import Navbar from "@/components/Navbar";
import ItineraryMap from "@/components/ItineraryMap";
import ItineraryViewer from "@/components/ItineraryViewer";
import type { ItineraryResponse, MapPoint } from "@/types/itinerary";

// ─── Dynamic OG Metadata ──────────────────────────────────────────────────────

export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  const trip = await prisma.trip.findUnique({ where: { id: params.id } });
  if (!trip) return { title: "Itinerary Not Found | Seek Wander" };

  return {
    title: `${trip.destination} Itinerary | Seek Wander`,
    description: `A curated luxury journey to ${trip.destination}, generated by Seek Wander.`,
    openGraph: {
      title: `${trip.destination} Itinerary | Seek Wander`,
      description: `A curated luxury journey to ${trip.destination}, generated by Seek Wander.`,
      type: "website",
    },
  };
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default async function SharedTripPage({
  params,
}: {
  params: { id: string };
}) {
  // Public route — intentionally no auth check.
  // Anyone with the link can view this itinerary.
  const trip = await prisma.trip.findUnique({ where: { id: params.id } });
  if (!trip) notFound();

  const itinerary = trip.itineraryData as unknown as ItineraryResponse;

  // Compute map points server-side — mirrors trips/[id]/page.tsx
  const mapPoints: MapPoint[] = (itinerary.days ?? []).flatMap((day) => {
    const pts: MapPoint[] = [
      {
        type: "morning",
        label: day.morning?.title ?? "",
        day: day.day,
        ...(day.morning?.coordinates ?? { lat: 0, lng: 0 }),
      },
      {
        type: "afternoon",
        label: day.afternoon?.title ?? "",
        day: day.day,
        ...(day.afternoon?.coordinates ?? { lat: 0, lng: 0 }),
      },
      {
        type: "evening",
        label: day.evening?.title ?? "",
        day: day.day,
        ...(day.evening?.coordinates ?? { lat: 0, lng: 0 }),
      },
      {
        type: "gem",
        label: day.hiddenGem?.split("—")?.[0]?.trim() ?? "",
        day: day.day,
        ...(day.hiddenGemCoordinates ?? { lat: 0, lng: 0 }),
      },
      ...(day.dining ?? []).map((d) => ({
        type: "dining" as const,
        label: d.name,
        day: day.day,
        ...(d.coordinates ?? { lat: 0, lng: 0 }),
      })),
    ];
    return pts.filter((p) => p.lat && p.lng);
  });

  const mapCenter =
    mapPoints.length > 0
      ? { lat: mapPoints[0].lat, lng: mapPoints[0].lng }
      : (itinerary.days?.[0]?.morning?.coordinates ?? {
          lat: 35.6762,
          lng: 139.6503,
        });

  // Bottom CTA — acquisition focused, no save button
  const bottomCta = (
    <div className="mt-14 border-t border-ink/5 pt-10 text-center pb-20 md:pb-10">
      <div className="w-8 h-px bg-burnt-orange mx-auto mb-8" />
      <p className="font-serif italic text-3xl text-ink mb-3">
        Inspired by this journey?
      </p>
      <p className="font-sans text-sm text-ink-light mb-8 max-w-xs mx-auto leading-relaxed">
        Seek Wander crafts bespoke luxury itineraries tailored to your pace,
        taste, and travel party &mdash; in seconds.
      </p>
      <Link
        href="/"
        className="micro-copy bg-burnt-orange text-white px-10 py-4 hover:bg-ink transition-colors duration-300 inline-block"
      >
        Curate Your Own Journey &rarr;
      </Link>
    </div>
  );

  return (
    <div className="h-screen flex flex-col bg-paper overflow-hidden">
      <Navbar />

      {/* ── Header: acquisition banner + destination info ── */}
      <div className="shrink-0 pt-20 border-b border-ink/5">

        {/* Acquisition bar — ink ribbon below navbar */}
        <div className="bg-ink px-6 md:px-10 py-3 flex items-center justify-between gap-4">
          <span className="micro-copy text-paper/40 hidden sm:inline">
            Shared Itinerary
          </span>
          <Link
            href="/"
            className="micro-copy text-paper hover:text-burnt-orange transition-colors duration-300 ml-auto"
          >
            Curated by Seek Wander &mdash; Create Your Own &rarr;
          </Link>
        </div>

        {/* Destination info */}
        <div className="bg-paper-dark px-6 md:px-10 py-5">
          <p className="micro-copy text-ink-light mb-1">
            {trip.days}&nbsp;{trip.days === 1 ? "Day" : "Days"}
            &ensp;&middot;&ensp;Public Itinerary
          </p>
          <h1 className="font-serif italic text-4xl md:text-6xl text-ink leading-none">
            {trip.destination}
          </h1>
        </div>
      </div>

      {/* ── Split-screen — 55/45 mirroring trips/[id] ── */}
      <div className="flex flex-1 min-h-0">

        {/* LEFT: Scrollable timeline */}
        <div className="w-full md:w-[55%] overflow-y-auto">

          {/* Mobile map banner */}
          <div className="md:hidden h-52 w-full border-b border-ink/5">
            <ItineraryMap center={mapCenter} points={mapPoints} />
          </div>

          <div className="px-6 md:px-10 py-8">
            <ItineraryViewer itinerary={itinerary} bottomSection={bottomCta} />
          </div>
        </div>

        {/* RIGHT: Sticky map */}
        <div className="hidden md:block w-[45%] border-l border-ink/5 h-full">
          <ItineraryMap center={mapCenter} points={mapPoints} />
        </div>
      </div>

      {/* ── Mobile sticky bottom CTA ── */}
      <div className="md:hidden fixed bottom-0 left-0 right-0 z-40">
        <Link
          href="/"
          className="flex items-center justify-center gap-2 bg-burnt-orange text-paper py-4 micro-copy hover:bg-ink transition-colors duration-300"
        >
          Curated by Seek Wander &mdash; Create Your Own &rarr;
        </Link>
      </div>
    </div>
  );
}
